CREATE TABLE tb_grupos (
    id_grupo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_grupo VARCHAR(100) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    id_usuario BIGINT NOT NULL
);

CREATE TABLE tb_dependentes (
    id_dependente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) UNIQUE,
    idade INT,
    parentesco VARCHAR(50),
    id_grupo BIGINT NOT NULL
);

ALTER TABLE tb_ingressos
ADD COLUMN id_dependente BIGINT;

ALTER TABLE tb_grupos
ADD CONSTRAINT fk_grupo_usuario FOREIGN KEY (id_usuario) REFERENCES tb_usuarios(id_usuario);

ALTER TABLE tb_dependentes
ADD CONSTRAINT fk_dependente_grupo FOREIGN KEY (id_grupo) REFERENCES tb_grupos(id_grupo);

ALTER TABLE tb_ingressos
ADD CONSTRAINT fk_ingresso_dependente FOREIGN KEY (id_dependente) REFERENCES tb_dependentes(id_dependente);
