CREATE TABLE tb_comunicados (
    id_comunicados BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    descricao VARCHAR(5000) NOT NULL,
    data_postagem TIMESTAMP WITH TIME ZONE DEFAULT now(),
    id_usuario BIGINT NOT NULL
);

ALTER TABLE tb_comunicados
ADD CONSTRAINT fk_comunicados_usuario FOREIGN KEY (id_usuario) REFERENCES tb_usuarios(id_usuario);