CREATE TABLE tb_pesquisa (
    id_pesquisa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(5000) NOT NULL,
    estrelas BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL
);

ALTER TABLE tb_pesquisa
ADD CONSTRAINT fk_pesquisa_usuario FOREIGN KEY (id_usuario) REFERENCES tb_usuarios(id_usuario);